### ISSUE TITLE
Appointment creation error with Evolution 

### ISSUE THREAD

**Issue by dmitry-112** [etesync/etesync-dav#10]
When trying to create an appointment with Evolution running on Debian 9, I get an error similar to the one shown below. This happens with every new appointment. This issue is cleared by restarting etesync-dav.
```
[7fc8fe6fa700] ERROR: An exception occurred during PUT request on '/XXXXXXXXX/dc93dfe5d268766a8e64489a5db3c864412f7faa4482d6763446a4aab1c0953d/20180221T153817Z-12741-1000-1-1_XXXXXX-20180221T154035Z.ics': <class 'etesync.pim.Content'> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS "t1" WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?)) LIMIT 1 OFFSET 0
Params: [2, '20180221T153817Z-12741-1000-1-1_XXXXXX-20180221T154035Z']
```

**Comment by tasn** [comment]
Thanks for reporting!
I got another report by email which looks exactly the same, but also had this line just before:

```
[7fc8a6194700] ERROR: An exception occurred during OPTIONS request on '/<EMAIL>/<HASH>/': uid
```

That user said it worked for him until he recently updated his system. Which I assume means something changed in Evolution. I need to further investigate it.

**Comment by dmitry-112** [comment]
The restart of etesync-dav is not required. The appointment is successfully created on the second attempt (clicking save a second time in the same window). It turns out that Evolution uses a different URI in the PUT following the failure. Each URI is provided below.

First attempt - fails:
http://localhost:37358/EMAIL/HASH/20180222T183650Z-1452-1000-1-32_HOST-20180222T183659Z.ics

Second attempt - works:
http://localhost:37358/EMAIL/HASH/20180222T183650Z-1452-1000-1-32@HOST

**Comment by tasn** [comment]
Could you try updating radicale, maybe Evolution now uses more features that were previously not implemented in Radicale but now are? Just a guess. I really don't know anything about DAV.

**Comment by dmitry-112** [comment]
I'm running the latest version of Radicale (2.1.8). I ran the tests again with debugging on in etesync-dav, and it looks like that what Evolution is passing along in the first attempt isn't allowing etesync to gather the proper user and journal information. Of course this is just a guess based on the debug output below, and looking at what's actually in the DB. The output below is just the error portion following the PUT attempt. Please let me know if the request headers would also be useful here.
```
[7f7f7899f700] ERROR: An exception occurred during PUT request on '/EMAIL/HASH/20180223T015441Z-29726-1000-1-3_HOST-20180223T015452Z.ics': Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS t1 WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?))
PARAMS: [3, '20180223T015441Z-29726-1000-1-3_HOST-20180223T015452Z']
Traceback (most recent call last):
  File "$HOME/.local/lib/python3.5/site-packages/peewee.py", line 3161, in get
    return next(clone.execute())
  File "$HOME/.local/lib/python3.5/site-packages/peewee.py", line 2326, in next
    obj = self.iterate()
  File "$HOME/.local/lib/python3.5/site-packages/peewee.py", line 2308, in iterate
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.local/lib/python3.5/site-packages/etesync/api.py", line 382, in get
    return self.get_content_class()._from_cache(self._cache_obj.content_set.where(pim.Content.uid == uid).get())
  File "$HOME/.local/lib/python3.5/site-packages/peewee.py", line 3165, in get
    % self.sql())
etesync.pim.ContentDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS t1 WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?))
PARAMS: [3, '20180223T015441Z-29726-1000-1-3_HOST-20180223T015452Z']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.local/lib/python3.5/site-packages/radicale/__init__.py", line 321, in __call__
    status, headers, answers = self._handle_request(environ)
  File "$HOME/.local/lib/python3.5/site-packages/radicale/__init__.py", line 494, in _handle_request
    environ, base_prefix, path, user)
  File "$HOME/.local/lib/python3.5/site-packages/radicale/__init__.py", line 910, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "$HOME/.local/lib/python3.5/site-packages/radicale_storage_etesync/__init__.py", line 350, in upload
    return self.get(href)
  File "$HOME/.local/lib/python3.5/site-packages/radicale_storage_etesync/__init__.py", line 320, in get
    etesync_item = self.collection.get(uid)
  File "$HOME/.local/lib/python3.5/site-packages/etesync/api.py", line 384, in get
    raise exceptions.DoesNotExist(e)
etesync.exceptions.DoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS t1 WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?))
PARAMS: [3, '20180223T015441Z-29726-1000-1-HOST-20180223T015452Z']
```

**Comment by tasn** [comment]
Sorry, forgot to reply to this one!
OK, I wonder then if it's an issue with how the radicale plugin works, or if it's an issue with Evolution. I'll have to take a better look this weekend, though as I said, I don't know much about Cal/CardDAV. :(

**Comment by tasn** [comment]
I updated all of the deps to the latest version of radicale, could you check if this solves it?

**Comment by tasn** [comment]
Just following up. Does it work now? I updated Radicale and all the deps again. :)

**Comment by dmitry-112** [comment]
I have not had a chance to test this since your Radicale update. I'll update this issue once I have.

**Comment by dmitry-112** [comment]
I've moved away from Evolution for a variety of reasons. I also switched distributions. I think this issue should be closed for now.

I started testing with TbSync in Thunderbird. I'll open a separate issue if I run into problems.

Thanks.

**Comment by tasn** [comment]
Thanks for letting me know. I'm leaving this open in case someone encounters it. If I hear nothing in a while, I'll close it.

I know for a fact evolution works for at least some users.

**Comment by marzzzello** [comment]
I have a similar error. Creating events is working fine. Just creating tasks gives me the following error every time:
```
[7f8a741af700] ERROR: An exception occurred during PUT request on '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/ee8e0a26e81f090a81475e61ef9f9752510eb71f.ics': vevent
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/peewee.py", line 6042, in get
  return clone.execute(database)[0]
File "/usr/lib/python3.7/site-packages/peewee.py", line 3729, in __getitem__
  return self.row_cache[item]
IndexError: list index out of range
```

<details>
  <summary>Full debug log</summary>
  
  ```
  etesync-dav -D 
[7fa2f9dbc600] INFO: Starting Radicale
[7fa2f9dbc600] INFO: Authentication type is 'htpasswd'
[7fa2f9dbc600] INFO: Storage type is 'radicale_storage_etesync'
[7fa2f9dbc600] INFO: Rights type is 'owner_only'
[7fa2f9dbc600] INFO: Web type is 'internal'
[7fa2f9dbc600] INFO: Listening to 'localhost' on port 37358
[7fa2f9dbc600] INFO: Radicale server ready
[7fa2f73fd700] INFO: PUT request for '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics' received from 127.0.0.1 using 'Evolution/3.30.4'
[7fa2f73fd700] DEBUG: Request headers:
{'CONTENT_LENGTH': '316',
 'CONTENT_TYPE': 'text/calendar; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_LANGUAGE': 'de-de, de;q=0.9',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'localhost:37358',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_PREFER': 'return=minimal',
 'HTTP_USER_AGENT': 'Evolution/3.30.4',
 'PATH_INFO': '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '37358',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7fa2f8593d38>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7fa2f73fd700] DEBUG: Sanitized script name: ''
[7fa2f73fd700] DEBUG: Sanitized path: '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics'
[7fa2f73fd700] INFO: Successful login: 'marzzzello'
[7fa2f73fd700] DEBUG: Request content:
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
VERSION:2.0
BEGIN:VTODO
UID:a1fc39aefa19c87188c8828d2984ac70b9feb896
DTSTAMP:20190126T154817Z
SUMMARY:new task...
PRIORITY:0
CLASS:PUBLIC
CREATED:20190126T162820Z
LAST-MODIFIED:20190126T162820Z
END:VTODO
END:VCALENDAR

[7fa2f73fd700] ERROR: An exception occurred during PUT request on '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics': vevent
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/peewee.py", line 6042, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.7/site-packages/peewee.py", line 3729, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 389, in get
    return self.get_content_class()._from_cache(self._cache_obj.content_set.where(pim.Content.uid == uid).get())
  File "/usr/lib/python3.7/site-packages/peewee.py", line 6047, in get
    (clone.model, sql, params))
etesync.pim.ContentDoesNotExist: <Model: Content> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS "t1" WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?)) LIMIT ? OFFSET ?
Params: [22, 'a1fc39aefa19c87188c8828d2984ac70b9feb896', 1, 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/radicale_storage_etesync/__init__.py", line 357, in upload
    item = self.get(href)
  File "/usr/lib/python3.7/site-packages/radicale_storage_etesync/__init__.py", line 335, in get
    etesync_item = self.collection.get(uid)
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 391, in get
    raise exceptions.DoesNotExist(e)
etesync.exceptions.DoesNotExist: <Model: Content> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS "t1" WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?)) LIMIT ? OFFSET ?
Params: [22, 'a1fc39aefa19c87188c8828d2984ac70b9feb896', 1, 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/vobject/base.py", line 529, in __getattr__
    return self.contents[toVName(name)][0]
KeyError: 'vevent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.7/site-packages/radicale/__init__.py", line 505, in _handle_request
    environ, base_prefix, path, user)
  File "/usr/lib/python3.7/site-packages/radicale/__init__.py", line 948, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "/usr/lib/python3.7/site-packages/radicale_storage_etesync/__init__.py", line 361, in upload
    etesync_item = self.collection.get_content_class().create(self.collection, content)
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 290, in create
    ret.content = content
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 300, in content
    self.uid = self.__class__.get_uid(content)
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 315, in get_uid
    return vobj.vevent.uid.value
  File "/usr/lib/python3.7/site-packages/vobject/base.py", line 531, in __getattr__
    raise AttributeError(name)
AttributeError: vevent
```
</details>

And I am a bit confused about the version output. Shouldn't it be `0.2.0`?
```
  etesync-dav --version
2.1.11
```

**Comment by tasn** [comment]
Hey @marzzzello, this means it's working for you. The tasks seems like a different issue. Could you please open a new ticket for that? I'll close this one as it seems like it's working.

As for the wrong version being printed: it's actually the version of radicale that it's showing and not etesync. Need to fix it to show both at some point.

Thanks!
