### ISSUE TITLE
"A server error occurred.  Please contact the administrator." (CalDav Synchronizer on Outlook for Windows)

### ISSUE THREAD

**Issue by tx3eh8IUD1** [etesync/etesync-dav#115]
Since the latest iOS update (fixing the N: ";" vs "," business), I get the following error in Outlook (as a Synchronization Report from the CalDAv Synchronizer Addin.

The Outlook -> Server (replicate) mode works all right for a different set of contacts 
The Server -> Outlook (replicate) mode used to work all right with the similar set of contacts. 

After the iOS update, I now get this error when trying to replicate Server -> Outlook:

The target folder in outlook is empty. I set up the connection again (fresh) but to no avail. 
```

CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '500' ('Internal Server Error'). Message:
A server error occurred.  Please contact the administrator.
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CardDavDataAccess.<GetAllVersions>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at CalDavSynchronizer.DataAccess.CardDavDataAccess.<GetAllVersions>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Contacts.CardDavEntityRepository`3.<GetAllVersions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.Contacts.LoggingCardDavRepositoryDecorator.<GetAllVersions>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.EntityRepositories.VersionAwareToStateAwareEntityRepositoryAdapter`4.<GetFullRepositoryState>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.EntityRepositories.Decorators.StateAwareEntityRepositoryRunInBackgroundDecorator`4.<GetFullRepositoryState>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`11.<Synchronize>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.ContextCreatingSynchronizerDecorator`7.<Synchronize>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Scheduling.SynchronizationProfileRunner.<RunAndRescheduleNoThrow>d__22.MoveNext()
```

edited: grammar.
tasn edit: put the backtrace in a code block instead of quote.

**Comment by tasn** [comment]
Hm... OK, so this is the error message from Outlook, I'd love to see the error message from `etesync-dav` though. I assume you are using the pre-compiled binary, is that correct? Would it be OK if I compiled a different binary that will enable us to better test the issue?

Also, does it happen consistently? What happens when you try to open the web UI and then click on e.g. the calendar or the address book? Do you get a file with all of your data or an error?

**Comment by tx3eh8IUD1** [comment]
Yes - happy to try any crazy files directly from you! Just let me know where to get everything from. I don't use encrypted-everything because I need to, I do it because I believe in cool software likes yours :)

It happens consistently **but only with this one address book** yes. No errors at all on the web-ui.

**Comment by tasn** [comment]
So opening this address book from the web ui works as expected and you get a vcard that has all of your contacts? If so, it looks like etesync-dav is maybe set up correctly. Could you try removing the account from outlook and then adding it back again?

**Comment by tx3eh8IUD1** [comment]
So the famous restart everything seems to have mended the issue. I have also re-added the folder (had done that prior to reporting, actually). 
Not sure what solved this - apologies. I will close it for now.

**Comment by tasn** [comment]
Please keep an eye out and let me know if it happens again. Glad to hear it's now fixed for you.
