### ISSUE TITLE
ModuleNotFoundError: No module named 'scrypt'

### ISSUE THREAD

**Issue by bigfatfrog67** [etesync/etesync-dav#155]
Tried running ./etesync-dav on Ubuntu 18.04.5 LTS

I get:

```
Traceback (most recent call last):
  File "site-packages/etesync/crypto.py", line 34, in <module>
ModuleNotFoundError: No module named 'scrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "etesync-dav", line 10, in <module>
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/etesync_dav/manage.py", line 21, in <module>
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/etesync/__init__.py", line 15, in <module>
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/etesync/api.py", line 20, in <module>
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/etesync/crypto.py", line 45, in <module>
ModuleNotFoundError: No module named 'pyscrypt'
[25766] Failed to execute script etesync-dav
```

Can't find any advice anywhere?

Jonathan

**Comment by tasn** [comment]
Oops, nice catch!
We changed how we build the pre-compiled binaries and it seems like it didn't work as expected on Linux. I now added tests to catch the next time it happens and I updated the binary in the releases page to a non-broken one.

Please let me know if you have any other issues.
