### ISSUE TITLE
Suport the CalDAV `MOVE` operation

### ISSUE THREAD

**Issue by tasn** [etesync/etesync-dav#183]
This is what you get when trying to do a `MOVE` at the moment:
```
Traceback (most recent call last):
  File "radicale/app/__init__.py", line 127, in __call__
  File "radicale/app/__init__.py", line 295, in _handle_request
  File "radicale/app/move.py", line 84, in do_MOVE
  File "etesync_dav/radicale/storage.py", line 576, in move
NotImplementedError
```

We can probably implement it internally as a create followed by deleting the original.
We should just change the href if the source and destination collection are the same.

**Comment by solarkraft** [comment]
Lack of support for this makes organizing my events a huge pain for me.

**Comment by solarkraft** [comment]
Let me add to my workaround:

- Do a full reload
- Remove the event that re-appeared in the old calendar

What a pain!
