### ISSUE TITLE
Error when setting up etesync-dav on Mac

### ISSUE THREAD

**Issue by ljanus** [etesync/etesync-dav#188]
This is on MacOS High Sierra 10.13.6.  When I initially run the etesync-dav it works fine and I am able to access http://localhost:37358/. After I enabled SSL (which requires a restart of the dav) I am now unable to access http://localhost:37358/. I ran the command line application to get more information and this is what I got:

> ~> /Users/me/Downloads/mac-etesync-dav/etesync-dav ; exit;
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "etesync-dav", line 155, in machack
  File "PyObjCTools/AppHelper.py", line 261, in runConsoleEventLoop
AttributeError: 'NoneType' object has no attribute 'earlierDate_'

When I attempted to access http://localhost:37358/ again I got these exceptions:

> [2020-12-04 19:56:13 -0800] [986/Thread-2] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-3] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-4] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-5] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-6] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-7] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-8] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-9] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-10] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)
[2020-12-04 19:56:13 -0800] [986/Thread-11] [ERROR] An exception occurred during request: SSL handshake failed: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)

Let me know if there is any additional information that could help. Thanks.

**Comment by tasn** [comment]
You opened it in in the wrong repo. I now transferred it over. Anyhow, as for the issue itself:
1. The first error you can ignore, it's a problem with a dep that doesn't actually affect anything.
2. Second error: you enable ssl, so you now need to use https://localhost:37358 . Use https not http.
