### ISSUE TITLE
An exception occurred during PROPFIND request on '/user/': Conflict

### ISSUE THREAD

**Issue by jdckr** [etesync/etesync-dav#189]
Hi!
I am facing the following error:
```
[2020-12-13 19:43:00 +0100] [6068/Thread-3] [ERROR] Conflict
Traceback (most recent call last):
  File "etesync_dav\radicale\storage.py", line 84, in run
  File "etesync_dav\local_cache\__init__.py", line 92, in sync
  File "etesync_dav\local_cache\__init__.py", line 157, in sync_collection
  File "etesync_dav\local_cache\__init__.py", line 220, in push_collection
  File "etebase\__init__.py", line 294, in batch
etebase_python.Error: Conflict
[2020-12-13 19:43:00 +0100] [6068/Thread-220] [ERROR] An exception occurred during PROPFIND request on '/user/': Conflict
[2020-12-13 19:43:45 +0100] [6068/Thread-3] [ERROR] Conflict
Traceback (most recent call last):
  File "etesync_dav\radicale\storage.py", line 84, in run
  File "etesync_dav\local_cache\__init__.py", line 92, in sync
  File "etesync_dav\local_cache\__init__.py", line 157, in sync_collection
  File "etesync_dav\local_cache\__init__.py", line 220, in push_collection
  File "etebase\__init__.py", line 294, in batch
etebase_python.Error: Conflict
[2020-12-13 19:43:45 +0100] [6068/Thread-222] [ERROR] An exception occurred during PROPFIND request on '/user/': Conflict
```
I already deleted `C:\Users\user\AppData\Local\etesync\etesync-dav` and set it up again. Unfortunately this didn't help.

My setup:
- Win10
- Thunderbird 78.5.1 (64-bit)
- TBSync 2.19
- etesync-dav 0.30.6

**Comment by tasn** [comment]
Interesting. What other clients do you use EteSync with? Are you using EteSync 2.0?

**Comment by jdckr** [comment]
Yes, I am using EteSync2.0.
There are another two Android devices connected to the server.

**Comment by tasn** [comment]
Could you please make sure to stop etesync-dav (make sure it's really stopped), and then set it up again? I know you did it already, but the only reason why a conflict could happen is if something is conflicting (so there is different data locally than what the server expects). Though to be honest, I don't even understand how a conflict is even possible in this line of code.

**Comment by jdckr** [comment]
I have set it up again. While doing so I observed `error trying to connect: dns error: No such host is known. (os error 11001)`.
I checked the firewall rules and couldn't find etesync. Added it manually and now it works.
Don't know what broke the firewall settings as I had it running already.

**Comment by tasn** [comment]
Ah, great to hear!
