### ISSUE TITLE
etesync-dav uses 1½ hours of CPU time in 43 hours

### ISSUE THREAD

**Issue by stuart12** [etesync/etesync-dav#206]
Etesync-dav uses too much CPU time and network bandwidth.  It would use even more CPU time if I didn't limit it with `CPUQuota=25%`  and `CPUSchedulingPolicy=batch.` At the moment,  I am using Thunderbird 78.8.0  without any active plugins so I am just synchronising my calendar.  Whenever I restart etesync-dav it downloads and uses the latest version without discarding the cache. I synchronise to my own etesync server at etesync.pook.it (I presume that you can probe it to see what version it is running). I have 2 Android devices also synchronising to my server.  How can I stop etesync-dav using so much CPU and network bandwidth?

I have just stopped Thunderbird and etesync-dav is still using 25% of a CPU (which is its limit).

```
:; systemctl status etesync-dav@stuart.service 
● etesync-dav@stuart.service - EteSync CalDAV and CardDAV front-end/proxy for stuart
     Loaded: loaded (/etc/systemd/system/etesync-dav@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/etesync-dav@.service.d
             └─override.conf
     Active: active (running) since Mon 2021-03-15 20:32:31 -03; 1 day 19h ago
       Docs: https://github.com/etesync/etesync-dav
    Process: 1692 ExecStartPre=mkdir -p -m 0700 $HOME $ETESYNC_DATA_DIR (code=exited, status=0/SUCCESS)
    Process: 1946 ExecStartPre=sh -c runuser -u stuart -- sh -c "tar -C \$HOME/.local/share/etesync-dav -hc $CONFFILES || tar -c --files-from /dev/null" > /run/etesync-dav@stuart/creds.tar (code=exited, status=0/SUCCESS)
    Process: 1950 ExecStartPre=tar -C ${ETESYNC_DATA_DIR} --unlink-first -f /run/etesync-dav@stuart/creds.tar -x (code=exited, status=0/SUCCESS)
    Process: 1952 ExecStartPre=pip3 --cache-dir /var/cache/etesync-dav@stuart/pip3-cache $PIP_ARGS install --no-warn-script-location $PIP_MODULES (code=exited, status=0/SUCCESS)
   Main PID: 1970 (etesync-dav)
         IP: 557.0K in, 10.8M out
      Tasks: 3 (limit: 50)
     Memory: 421.9M (high: 512.0M)
        CPU: 1h 32min 36.137s
     CGroup: /system.slice/system-etesync\x2ddav.slice/etesync-dav@stuart.service
             └─1970 /usr/bin/python3 /tmp/etesync-dav@stuart/.local/bin/etesync-dav
```

My etesync server prints messages such as:
```
2021-03-17T18:41:32.192471842Z INFO:     192.168.42.2:55026 - "GET /console/ HTTP/1.0" 400 Bad Request
2021-03-17T18:41:32.522418456Z INFO:     192.168.42.2:55030 - "POST /Autodiscover/Autodiscover.xml HTTP/1.0" 400 Bad Request
2021-03-17T18:41:34.249626258Z INFO:     192.168.42.2:55032 - "GET /_ignition/execute-solution HTTP/1.0" 400 Bad Request
2021-03-17T18:41:34.299202906Z INFO:     192.168.42.2:55034 - "POST /api/jsonws/invoke HTTP/1.0" 400 Bad Request
2021-03-17T18:41:36.619093762Z INFO:     192.168.42.2:55036 - "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.0" 400 Bad Request
2021-03-17T18:41:45.040204297Z INFO:     192.168.42.2:55044 - "POST /api/v1/collection/list_multi/?stoken=pc1AlpWckxHuSZtJTLfOYDilYcuChCcP HTTP/1.0" 200 OK
2021-03-17T18:50:29.101211188Z INFO:     192.168.42.2:58584 - "POST /api/v1/collection/list_multi/?stoken=pc1AlpWckxHuSZtJTLfOYDilYcuChCcP HTTP/1.0" 200 OK
2021-03-17T18:53:36.543757861Z INFO:     192.168.42.2:59186 - "GET /api/v1/user/stuart/ HTTP/1.0" 404 Not Found
2021-03-17T18:53:37.931884646Z INFO:     192.168.42.2:59188 - "POST /api/v1/user/ HTTP/1.0" 404 Not Found
2021-03-17T18:56:46.388071984Z INFO:     192.168.42.2:59868 - "POST /api/v1/collection/list_multi/?stoken=pc1AlpWckxHuSZtJTLfOYDilYcuChCcP HTTP/1.0" 200 OK
2021-03-17T18:58:05.220708580Z INFO:     192.168.42.2:60112 - "POST /api/v1/collection/list_multi/?stoken=g5ymeRuqr1rXoTWQlVCv-etd5I-93fxL HTTP/1.0" 200 OK
2021-03-17T18:58:06.239277405Z INFO:     192.168.42.2:60118 - "GET /api/v1/collection/J_NqYOvKup7OiE7Dn4Fn7t31rog8u323/item/?stoken=qR94vly7_HVfX4LLQbF0KVZ15xd15eJB HTTP/1.0" 200 OK
2021-03-17T18:58:12.630768069Z INFO:     192.168.42.2:60170 - "POST /api/v1/collection/list_multi/?stoken=pc1AlpWckxHuSZtJTLfOYDilYcuChCcP HTTP/1.0" 200 OK
2021-03-17T19:01:50.097499109Z INFO:     192.168.42.2:60898 - "POST /api/v1/collection/list_multi/?stoken=pc1AlpWckxHuSZtJTLfOYDilYcuChCcP HTTP/1.0" 200 OK
```
A strace, `sudo strace -t -s4 -fp 1970,` on the etesync process shows:
```
[pid 735918] 16:15:55 getrandom("\x95\x06\xc8\x3a"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16891904) = 4096
[pid 735918] 16:15:56 pread64(13, "\n\0\0\0"..., 4096, 30322688) = 4096
[pid 735918] 16:15:56 getrandom("\xdb\x4c\xca\xf2"..., 16, 0) = 16
[pid 735918] 16:15:56 mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efc054c0000
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16896000) = 4096
[pid 735918] 16:15:56 getrandom("\x07\x3a\x70\xa5"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16900096) = 4096
[pid 735918] 16:15:56 pread64(13, "\n\0\0\0"..., 4096, 30691328) = 4096
[pid 735918] 16:15:56 getrandom("\x18\x38\xdf\x4b"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16904192) = 4096
[pid 735918] 16:15:56 getrandom("\x63\x85\xc4\xed"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16908288) = 4096
[pid 735918] 16:15:56 getrandom("\xf9\x77\xea\xfb"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16912384) = 4096
[pid 735918] 16:15:56 getrandom("\xfc\x1a\x64\x4c"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16916480) = 4096
[pid 735918] 16:15:56 getrandom("\xa4\xa6\x72\x15"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16920576) = 4096
[pid 735918] 16:15:56 getrandom("\xae\x71\x59\x8c"..., 16, 0) = 16
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16928768) = 4096
[pid 735918] 16:15:56 getrandom("\xf9\x91\x51\x89"..., 16, 0) = 16
[pid 735918] 16:15:56 mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efc05480000
[pid 735918] 16:15:56 pread64(13, "\r\0\0\0"..., 4096, 16932864) = 4096
[pid 735918] 16:15:56 getrandom("\x26\xc4\x80\x7d"..., 16, 0) = 16
[pid 735918] 16:15:57 pread64(13, "\r\0\0\0"..., 4096, 16936960) = 4096

```
PS. How can I tell what version my server is running?

And many thanks for giving us etesync.

**Comment by tasn** [comment]
Server is running: there's no easy way.
It looks like it's stuck in a loop for whatever reason. It will be hard to debug... :| You can also try the nuclear option of stopping etesync-dav, moving over the data dir, and starting with etesync-dav from scratch (it'll sync once and then it'll be the same). I really have no idea what's up. :(

**Comment by stuart12** [comment]
hi, we discussed this problem a few months ago on Matrix. What do I need to copy over? I presume that I can just delete the cache and it will be rebuilt.  I have removed all plugins from Thunderbird (78.8.0) and am just syncing the calendar using the built-in connector. (TbSync refused to even contact my etesync-dav server on localhost.)

It appears that I'm running whatever code I got when [I cloned https://github.com/etesync/server.git](https://github.com/stuart12/server-container-configuration/blob/master/containers/etesync/Dockerfile). I should put the SHA1 in a file.

I also download my contacts using a [python script](https://github.com/stuart12/python-scripts/blob/master/ring) every day or so.

I don't see what I could be doing to make etesync-dav loop. it doesn't immediately start looping. At the moment it isn't but it has exchanged a lot of data for 29 hours.
```
● etesync-dav@stuart.service - EteSync CalDAV and CardDAV front-end/proxy for stuart
     Loaded: loaded (/etc/systemd/system/etesync-dav@.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/etesync-dav@.service.d
             └─override.conf
     Active: active (running) since Wed 2021-03-17 16:27:05 -03; 1 day 5h ago
       Docs: https://github.com/etesync/etesync-dav
    Process: 736582 ExecStartPre=mkdir -p -m 0700 $HOME $ETESYNC_DATA_DIR (code=exited, status=0/SUCCESS)
    Process: 736586 ExecStartPre=sh -c runuser -u stuart -- sh -c "tar -C \$HOME/.local/share/etesync-dav -hc $CONFFILES || tar -c --files-from /dev/null" > /run/etesync-dav@stuart/creds.tar (code=exited, status=0/SUCCESS)
    Process: 736590 ExecStartPre=tar -C ${ETESYNC_DATA_DIR} --unlink-first -f /run/etesync-dav@stuart/creds.tar -x (code=exited, status=0/SUCCESS)
    Process: 736593 ExecStartPre=pip3 --cache-dir /var/cache/etesync-dav@stuart/pip3-cache $PIP_ARGS install --no-warn-script-location $PIP_MODULES (code=exited, status=0/SUCCESS)
   Main PID: 736606 (etesync-dav)
         IP: 1.1M in, 2.4M out
      Tasks: 4 (limit: 50)
     Memory: 379.1M (high: 512.0M)
        CPU: 12min 45.505s
     CGroup: /system.slice/system-etesync\x2ddav.slice/etesync-dav@stuart.service
             └─736606 /usr/bin/python3 /tmp/etesync-dav@stuart/.local/bin/etesync-dav
```

**Comment by stuart12** [comment]
hi, I think that I need to fix this problem or stop using etesync. Can you suggest a python profiler or give any more advice on how to debug this problem? Not only does etesync-dav use all the cpu time that it can get but thunderbird also losses updates to calendar entries and says 

```
An error occurred when writing to the calendar etesync! Please see below for more information.
Error code: MODIFICATION_FAILED
Description:
```

Etesync-dav says:

```
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]: [2021-11-11 11:26:59 +0100] [1862/Thread-3] [ERROR] database is locked
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]: Traceback (most recent call last):
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 3144, in execute_sql
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     cursor.execute(sql, params or ())
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]: sqlite3.OperationalError: database is locked
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]: During handling of the above exception, another exception occurred:
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]: Traceback (most recent call last):
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.9/site-packages/etesync_dav/radicale/storage.py", line 84, in run
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     etesync.sync()
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.9/site-packages/etesync_dav/local_cache/__init__.py", line 92, in sync
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     self.sync_collection(collection.uid)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.9/site-packages/etesync_dav/local_cache/__init__.py", line 157, in sync_collection
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     self.push_collection(uid)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.9/site-packages/etesync_dav/local_cache/__init__.py", line 225, in push_collection
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     cache_item.save()
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 6554, in save
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     rows = self.update(**field_dict).where(self._pk_expr()).execute()
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 1907, in inner
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     return method(self, database, *args, **kwargs)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 1978, in execute
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     return self._execute(database)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 2474, in _execute
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     cursor = database.execute(self)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 3157, in execute
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     return self.execute_sql(sql, params, commit=commit)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 3151, in execute_sql
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     self.commit()
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 2917, in __exit__
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     reraise(new_type, new_type(exc_value, *exc_args), traceback)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 190, in reraise
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     raise value.with_traceback(tb)
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:   File "/usr/lib/python3/dist-packages/peewee.py", line 3144, in execute_sql
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]:     cursor.execute(sql, params or ())
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]: peewee.OperationalError: database is locked
Nov 11 11:26:59 spook-7480latitude etesync-dav[1862]: [2021-11-11 11:26:59 +0100] [1862/Thread-31] [ERROR] An exception occurred during PUT request on '/stuart/J_NqYOvKup7OiE7Dn4Fn7t31XXXXXXXXXXXX08-44e6-b2a4-3bbddd3c7171.ics': database is locked
```
Should I restart etesync when I see **database is locked**?

This thunderbird is not using any add-ons. My other machine had the tbsync add-on and saw the same errors (until its CPU fried).

**Comment by tasn** [comment]
Interesting that you are still getting the database is locked error, I wonder why it happens. :|
Either way, this error should be recoverable I believe.

Anyhow, for a profile, I've previously used: https://github.com/benfred/py-spy

**Comment by stuart12** [comment]
My etebase_data.db is 31 MB (32342016 bytes). Is this unusually big? Do I have more calendar entries than normal?
