### ISSUE TITLE
etesync-dav fails with: <Model: CollectionEntity> instance matching query does not exist

### ISSUE THREAD

**Issue by stuart12** [etesync/etesync-dav#234]
hello, I have upgraded my etesync-v2 server to 453869d71d04b2bc454126e60515aa09a7bcb8b9 (the latest at the moment) and my etesync-dav is Radicale-3.0.6 etebase-0.31.2 etesync-0.12.1 etesync-dav-0.30.8 . When I start with new instance of etesync-dav without any cache files and try to access my contacts, etesync-dav says:

Oct 09 18:01:11 kooka etesync-dav[193631]: [2021-10-09 18:01:11 +0200] [193631/Thread-4] [ERROR] An exception occurred during GET request on '/stuart/8f????????????????????????????f2d/': <Model: CollectionEntity> instance matching query does not exist:
Oct 09 18:01:11 kooka etesync-dav[193631]: SQL: SELECT "t1"."id", "t1"."local_user_id", "t1"."uid", "t1"."eb_col", "t1"."new", "t1"."dirty", "t1"."deleted", "t1"."stoken", "t1"."local_stoken" FROM "collectionentity" AS "t1" WHERE (("t1"."local_user_id" = ?) AND (("t1"."uid" = ?) AND NOT "t1"."deleted")) LIMIT ? OFFSET ?
Oct 09 18:01:11 kooka etesync-dav[193631]: Params: [1, '8f3b????????????????????????????2d', 1, 0]

And my client gets a 500 reply from etesync-dav.

The etesync-v2 server just logs:
INFO:     192.168.42.2:53284 - "POST /api/v1/collection/list_multi/?stoken=C7???????????qFW HTTP/1.0" 200 OK
INFO:     192.168.42.2:53288 - "GET /api/v1/collection/J_Nq???????u323/item/?stoken=C????????????W HTTP/1.0" 200 OK

Does anybody know what is going on?

**Comment by stuart12** [comment]
Hello, I found why my client received a 500 (I was using the wrong URL).  I still have this error message (this time on a different machine):
```
Oct 10 14:48:55 spook-7480latitude etesync-dav[18257]: [2021-10-10 14:48:55 +0200] [18257/Thread-1] [ERROR] An exception occurred during GET request on '/stuart/U????????????Q/': <Model: CollectionEntity> instance matching query does not exist:
Oct 10 14:48:55 spook-7480latitude etesync-dav[18257]: SQL: SELECT "t1"."id", "t1"."local_user_id", "t1"."uid", "t1"."eb_col", "t1"."new", "t1"."dirty", "t1"."deleted", "t1"."stoken", "t1"."local_stoken" FROM "collectionentity" AS "t1" WHERE (("t1"."local_user_id" = ?) AND (("t1"."uid" = ?) AND NOT ">
Oct 10 14:48:55 spook-7480latitude etesync-dav[18257]: Params: [1, 'U???????????Q', 1, 0]
```
but etesync-dav works. If the error message should just be ignored, please close this ticket.

**Comment by tasn** [comment]
:|
I still haven't managed to reproduce that.

**Comment by stuart12** [comment]
Hi @tasn this problem is still present. Etesync-dav and thunderbird were refusing to work (thunderbird was not getting any new calendar entries), so I stopped etesync-dav and removed  `etebase_data.db`. When I restart etesync-dav I see
```
Jun 12 10:02:24 xps9320 python3[35554]: Installing collected packages: pytz, peewee, passlib, msgpack, asn1crypto, appdirs, urllib3, six, PySocks, pyparsing, pycparser, pyasn1, py, packaging, MarkupSafe, itsdangerous, idna, etebase, defusedxml, click, charset-normalizer, certifi, blinker, WTForms, Werkzeug, requests, python-dateutil, orderedmultidict, Jinja2, cffi, vobject, furl, Flask, cryptography, Radicale, Flask-WTF, etesync, etesync-dav
Jun 12 10:02:25 xps9320 python3[35554]: Successfully installed Flask-2.3.2 Flask-WTF-0.15.1 Jinja2-3.1.2 MarkupSafe-2.1.3 PySocks-1.7.1 Radicale-3.1.8 WTForms-3.0.1 Werkzeug-2.3.6 appdirs-1.4.4 asn1crypto-1.5.1 blinker-1.6.2 certifi-2023.5.7 cffi-1.15.1 charset-normalizer-3.1.0 click-8.1.3 cryptography-41.0.1 defusedxml-0.7.1 etebase-0.31.5 etesync-0.12.1 etesync-dav-0.32.1 furl-2.1.3 idna-3.4 itsdangerous-2.1.2 msgpack-1.0.5 orderedmultidict-1.0.1 packaging-23.1 passlib-1.7.4 peewee-3.16.2 py-1.11.0 pyasn1-0.5.0 pycparser-2.21 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2023.3 requests-2.31.0 six-1.16.0 urllib3-2.0.3 vobject-0.9.6.1
Jun 12 10:02:25 xps9320 systemd[1]: Started EteSync CalDAV and CardDAV front-end/proxy for stuart.
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] Loaded default config
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] Loaded arguments
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] Starting Radicale
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] auth type is 'radicale.auth.htpasswd'
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] storage type is 'etesync_dav.radicale.storage'
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] rights type is 'etesync_dav.radicale.rights'
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] web type is 'etesync_dav.radicale.web'
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] Listening on '[127.0.0.1]:37358'
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] Listening on '[::1]:37358'
Jun 12 10:02:26 xps9320 python3[35560]: [2023-06-12 10:02:26 +0200] [35560] [INFO] Radicale server ready
Jun 12 10:02:35 xps9320 python3[35560]: [2023-06-12 10:02:35 +0200] [35560/Thread-1 (process_request_thread)] [INFO] GET request for '/stuart/xx/' received from 127.0.0.1 using 'python-requests/2.25.1'
Jun 12 10:02:35 xps9320 python3[35560]: [2023-06-12 10:02:35 +0200] [35560/Thread-1 (process_request_thread)] [INFO] Successful login: 'stuart'
Jun 12 10:02:35 xps9320 python3[35560]: [2023-06-12 10:02:35 +0200] [35560/Thread-1 (process_request_thread)] [ERROR] An exception occurred during GET request on '/stuart/xx/': <Model: CollectionEntity> instance matching query does not exist:
Jun 12 10:02:35 xps9320 python3[35560]: SQL: SELECT "t1"."id", "t1"."local_user_id", "t1"."uid", "t1"."eb_col", "t1"."new", "t1"."dirty", "t1"."deleted", "t1"."stoken", "t1"."local_stoken" FROM "collectionentity" AS "t1" WHERE (("t1"."local_user_id" = ?) AND (("t1"."uid" = ?) AND NOT "t1"."deleted")) LIMIT ? OFFSET ?
Jun 12 10:02:35 xps9320 python3[35560]: Params: [1, 'xx', 1, 0]
Jun 12 10:02:35 xps9320 python3[35560]: [2023-06-12 10:02:35 +0200] [35560/Thread-2] [ERROR] Invalid token.
Jun 12 10:02:35 xps9320 python3[35560]: Traceback (most recent call last):
Jun 12 10:02:35 xps9320 python3[35560]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.10/site-packages/etesync_dav/radicale/storage.py", line 84, in run
Jun 12 10:02:35 xps9320 python3[35560]:     etesync.sync()
Jun 12 10:02:35 xps9320 python3[35560]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.10/site-packages/etesync_dav/local_cache/__init__.py", line 90, in sync
Jun 12 10:02:35 xps9320 python3[35560]:     self.sync_collection_list()
Jun 12 10:02:35 xps9320 python3[35560]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.10/site-packages/etesync_dav/local_cache/__init__.py", line 104, in sync_collection_list
Jun 12 10:02:35 xps9320 python3[35560]:     col_list = col_mgr.list(COL_TYPES, fetch_options)
Jun 12 10:02:35 xps9320 python3[35560]:   File "/tmp/etesync-dav@stuart/.local/lib/python3.10/site-packages/etebase/__init__.py", line 247, in list
Jun 12 10:02:35 xps9320 python3[35560]:     return CollectionListResponse(self._inner.list_multi(list(col_type), _inner(fetch_options)))
Jun 12 10:02:35 xps9320 python3[35560]: etebase_python.Error: Invalid token.
Jun 12 10:02:36 xps9320 python3[35560]: [2023-06-12 10:02:36 +0200] [35560/Thread-3 (process_request_thread)] [INFO] GET request for '/stuart/xx/' received from 127.0.0.1 using 'python-requests/2.25.1'
Jun 12 10:02:36 xps9320 python3[35560]: [2023-06-12 10:02:36 +0200] [35560/Thread-3 (process_request_thread)] [INFO] Successful login: 'stuart'
Jun 12 10:02:36 xps9320 python3[35560]: [2023-06-12 10:02:36 +0200] [35560/Thread-3 (process_request_thread)] [ERROR] An exception occurred during GET request on '/stuart/xx/': Invalid token.
Jun 12 10:02:37 xps9320 python3[35560]: [2023-06-12 10:02:37 +0200] [35560/Thread-4 (process_request_thread)] [INFO] GET request for '/stuart/xx/' received from 127.0.0.1 using 'python-requests/2.25.1'
Jun 12 10:02:37 xps9320 python3[35560]: [2023-06-12 10:02:37 +0200] [35560/Thread-4 (process_request_thread)] [INFO] Successful login: 'stuart'
Jun 12 10:02:37 xps9320 python3[35560]: [2023-06-12 10:02:37 +0200] [35560/Thread-4 (process_request_thread)] [ERROR] An exception occurred during GET request on '/stuart/xx/': <Model: CollectionEntity> instance matching query does not exist:
Jun 12 10:02:37 xps9320 python3[35560]: SQL: SELECT "t1"."id", "t1"."local_user_id", "t1"."uid", "t1"."eb_col", "t1"."new", "t1"."dirty", "t1"."deleted", "t1"."stoken", "t1"."local_stoken" FROM "collectionentity" AS "t1" WHERE (("t1"."local_user_id" = ?) AND (("t1"."uid" = ?) AND NOT "t1"."deleted")) LIMIT ? OFFSET ?
Jun 12 10:02:37 xps9320 python3[35560]: Params: [1, 'xx', 1, 0]
Jun 12 10:02:38 xps9320 python3[35560]: [2023-06-12 10:02:38 +0200] [35560/Thread-5 (process_request_thread)] [INFO] GET request for '/stuart/xx/' received from 127.0.0.1 using 'python-requests/2.25.1'
Jun 12 10:02:38 xps9320 python3[35560]: [2023-06-12 10:02:38 +0200] [35560/Thread-5 (process_request_thread)] [INFO] Successful login: 'stuart'
Jun 12 10:02:38 xps9320 python3[35560]: [2023-06-12 10:02:38 +0200] [35560/Thread-5 (process_request_thread)] [ERROR] An exception occurred during GET request on '/stuart/xx/': <Model: CollectionEntity> instance matching query does not exist:
Jun 12 10:02:38 xps9320 python3[35560]: SQL: SELECT "t1"."id", "t1"."local_user_id", "t1"."uid", "t1"."eb_col", "t1"."new", "t1"."dirty", "t1"."deleted", "t1"."stoken", "t1"."local_stoken" FROM "collectionentity" AS "t1" WHERE (("t1"."local_user_id" = ?) AND (("t1"."uid" = ?) AND NOT "t1"."deleted")) LIMIT ? OFFSET ?
Jun 12 10:02:38 xps9320 python3[35560]: Params: [1, 'xx', 1, 0]
Jun 12 10:02:39 xps9320 python3[35560]: [2023-06-12 10:02:39 +0200] [35560/Thread-6 (process_request_thread)] [INFO] GET request for '/stuart/xx/' received from 127.0.0.1 using 'python-requests/2.25.1'
Jun 12 10:02:39 xps9320 python3[35560]: [2023-06-12 10:02:39 +0200] [35560/Thread-6 (process_request_thread)] [INFO] Successful login: 'stuart'
Jun 12 10:02:39 xps9320 python3[35560]: [2023-06-12 10:02:39 +0200] [35560/Thread-6 (process_request_thread)] [ERROR] An exception occurred during GET request on '/stuart/xx/': <Model: CollectionEntity> instance matching query does not exist:
Jun 12 10:02:39 xps9320 python3[35560]: SQL: SELECT "t1"."id", "t1"."local_user_id", "t1"."uid", "t1"."eb_col", "t1"."new", "t1"."dirty", "t1"."deleted", "t1"."stoken", "t1"."local_stoken" FROM "collectionentity" AS "t1" WHERE (("t1"."local_user_id" = ?) AND (("t1"."uid" = ?) AND NOT "t1"."deleted")) LIMIT ? OFFSET ?
Jun 12 10:02:39 xps9320 python3[35560]: Params: [1, 'xx', 1, 0]
Jun 12 10:02:40 xps9320 python3[35560]: [2023-06-12 10:02:40 +0200] [35560/Thread-7 (process_request_thread)] [INFO] GET request for '/stuart/xx/' received from 127.0.0.1 using 'python-requests/2.25.1'
```
Queries to etesync-dav get 500 responses.  Connecting to http://localhost:37358/ gives `A server error occurred.  Please contact the administrator`.

Etesync-dav has become essential to my daily workflow so please let me know if I can help debug this problem.

**Comment by stuart12** [comment]
As a sign of  increasing desperation, I tried removing `etesync_creds` as well. Now I see:
```Jun 12 13:22:35 xps9320 python3[4652]: Installing collected packages: pytz, peewee, passlib, msgpack, asn1crypto, appdirs, urllib3, six, PySocks, pyparsing, pycparser, pyasn1, py, packaging, MarkupSafe, itsdangerous, idna, etebase, defusedxml, click, charset-normalizer, certifi, blinker, WTForms, Werkzeug, requests, python-dateutil, orderedmultidict, Jinja2, cffi, vobject, furl, Flask, cryptography, Radicale, Flask-WTF, etesync, etesync-dav
Jun 12 13:22:36 xps9320 python3[4652]: Successfully installed Flask-2.3.2 Flask-WTF-0.15.1 Jinja2-3.1.2 MarkupSafe-2.1.3 PySocks-1.7.1 Radicale-3.1.8 WTForms-3.0.1 Werkzeug-2.3.6 appdirs-1.4.4 asn1crypto-1.5.1 blinker-1.6.2 certifi-2023.5.7 cffi-1.15.1 charset-normalizer-3.1.0 click-8.1.3 cryptography-41.0.1 defusedxml-0.7.1 etebase-0.31.5 etesync-0.12.1 etesync-dav-0.32.1 furl-2.1.3 idna-3.4 itsdangerous-2.1.2 msgpack-1.0.5 orderedmultidict-1.0.1 packaging-23.1 passlib-1.7.4 peewee-3.16.2 py-1.11.0 pyasn1-0.5.0 pycparser-2.21 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2023.3 requests-2.31.0 six-1.16.0 urllib3-2.0.3 vobject-0.9.6.1
Jun 12 13:22:36 xps9320 systemd[1]: Started EteSync CalDAV and CardDAV front-end/proxy for stuart.
Jun 12 13:22:36 xps9320 python3[4657]: [2023-06-12 13:22:36 +0200] [4657] [INFO] Loaded default config
Jun 12 13:22:36 xps9320 python3[4657]: [2023-06-12 13:22:36 +0200] [4657] [INFO] Loaded arguments
Jun 12 13:22:36 xps9320 python3[4657]: [2023-06-12 13:22:36 +0200] [4657] [INFO] Starting Radicale
Jun 12 13:22:37 xps9320 python3[4657]: [2023-06-12 13:22:37 +0200] [4657] [INFO] auth type is 'radicale.auth.htpasswd'
Jun 12 13:22:37 xps9320 python3[4657]: [2023-06-12 13:22:37 +0200] [4657] [INFO] storage type is 'etesync_dav.radicale.storage'
Jun 12 13:22:37 xps9320 python3[4657]: [2023-06-12 13:22:37 +0200] [4657] [INFO] rights type is 'etesync_dav.radicale.rights'
Jun 12 13:22:37 xps9320 python3[4657]: [2023-06-12 13:22:37 +0200] [4657] [INFO] web type is 'etesync_dav.radicale.web'
Jun 12 13:22:37 xps9320 python3[4657]: [2023-06-12 13:22:37 +0200] [4657] [INFO] Listening on '[127.0.0.1]:37358'
Jun 12 13:22:37 xps9320 python3[4657]: [2023-06-12 13:22:37 +0200] [4657] [INFO] Listening on '[::1]:37358'
Jun 12 13:22:37 xps9320 python3[4657]: [2023-06-12 13:22:37 +0200] [4657] [INFO] Radicale server ready
Jun 12 13:22:51 xps9320 python3[4657]: [2023-06-12 13:22:51 +0200] [4657/Thread-1 (process_request_thread)] [INFO] GET request for '/' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0'
Jun 12 13:22:51 xps9320 python3[4657]: [2023-06-12 13:22:51 +0200] [4657/Thread-1 (process_request_thread)] [INFO] GET response status for '/' in 0.001 seconds: 302 Found
Jun 12 13:22:54 xps9320 python3[4657]: [2023-06-12 13:22:54 +0200] [4657/Thread-3 (process_request_thread)] [INFO] GET request for '/' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0'
Jun 12 13:22:54 xps9320 python3[4657]: [2023-06-12 13:22:54 +0200] [4657/Thread-3 (process_request_thread)] [INFO] GET response status for '/' in 0.001 seconds: 302 Found
Jun 12 13:22:54 xps9320 python3[4657]: [2023-06-12 13:22:54 +0200] [4657/Thread-4 (process_request_thread)] [INFO] GET request for '/.web' received from 127.0.0.1 using 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0'
Jun 12 13:22:54 xps9320 python3[4657]: [2023-06-12 13:22:54 +0200] [4657/Thread-4 (process_request_thread)] [ERROR] An exception occurred during GET request on '/.web': module 'flask.json' has no attribute 'JSONEncoder'
```

**Comment by stuart12** [comment]
I got etesync working again. I had to force Flask==2.2.3 for the `has no attribute 'JSONEncoder'` error.

The `etebase_python.Error: Invalid token` was the relevant message. I had to remove `etesync_creds` to get a new token. Please consider catching this exception and making this suggestion.

I was confused (again) by the `[ERROR] An exception occurred during GET request on '/stuart/xx/': <Model: CollectionEntity>` message. Please consider downgrading this message to a warning as it does not seem to be an error as I still get this "error" even when etesync is working fine.

thanks for etesync

**Comment by stuart12** [comment]
[Flask 2.2.5](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-2-5) might have been better thabn 2.2.3

**Comment by stuart12** [comment]
[Flask 2.2.5](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-2-5) might have been better than 2.2.3
