### ISSUE TITLE
At startup: TypeError: static_init() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by stuart12** [etesync/etesync-dav#28]
hello, a new installation of etesync-dav no longer starts with an error message from radical.  Is this a [pinning](https://nvie.com/posts/pin-your-packages/) problem?
```
: ; /usr/bin/python3 -m venv /tmp/issue
: ; . /tmp/issue/bin/activate
(issue) : ; pip install  etesync-dav
Collecting etesync-dav
  Using cached https://files.pythonhosted.org/packages/58/03/d7ff3bb8281f14dda4f43c1a19649e5c0c451fd92074965f7d892bbd337a/etesync_dav-0.1.6-py3-none-any.whl
Collecting appdirs>=1.4.3 (from etesync-dav)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting radicale-storage-etesync>=0.1.5 (from etesync-dav)
  Using cached https://files.pythonhosted.org/packages/58/b3/60e294dd83a606aae92250ec1369a628361836d0b0629a9a71e34f0d55d6/radicale_storage_etesync-0.1.5-py3-none-any.whl
Collecting Radicale>=2.1.9 (from radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting etesync>=0.5.4 (from radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/01/aa/56014a882d855b74fa5c4b0dbf8202772cee2c3980d90b65256653af5df6/etesync-0.5.4-py3-none-any.whl
Collecting vobject>=0.9.6 (from Radicale>=2.1.9->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting python-dateutil>=2.7.3 (from Radicale>=2.1.9->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting orderedmultidict>=0.7 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting pycparser>=2.17 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting py>=1.4 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/f3/bd/83369ff2dee18f22f27d16b78dd651e8939825af5f8b0b83c38729069962/py-1.5.4-py2.py3-none-any.whl
Collecting requests>=2.13 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting six>=1.10 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pyasn1>=0.2 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Collecting furl>=0.5 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting peewee<3.0,>=2.9 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting coverage>=4.3 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/3d/a0/b12090c40e0b8196b973962ec71c1c541a6c04af58ba5ad85683b3de251a/coverage-4.5.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyscrypt>=1.6 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting idna>=2.5 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting asn1crypto>=0.22 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting pyparsing>=2.2 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting packaging>=16.8 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Collecting cryptography>=1.9 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/59/32/92cade62c645756a83598edf56289e9b19aae5370642a7ce690cd06bc72f/cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl
Collecting cffi>=1.10 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13->etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.13->etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.13->etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/16/1f/50d729c104b21c1042aa51560da6141d1cab476ba7015d92b2111c8db841/certifi-2018.8.13-py2.py3-none-any.whl
Installing collected packages: appdirs, six, python-dateutil, vobject, Radicale, orderedmultidict, pycparser, py, chardet, idna, urllib3, certifi, requests, pyasn1, furl, peewee, coverage, pyscrypt, asn1crypto, pyparsing, packaging, cffi, cryptography, etesync, radicale-storage-etesync, etesync-dav
Successfully installed Radicale-2.1.10 appdirs-1.4.3 asn1crypto-0.24.0 certifi-2018.8.13 cffi-1.11.5 chardet-3.0.4 coverage-4.5.1 cryptography-2.3.1 etesync-0.5.4 etesync-dav-0.1.6 furl-1.2.1 idna-2.7 orderedmultidict-1.0 packaging-17.1 peewee-2.10.2 py-1.5.4 pyasn1-0.4.4 pycparser-2.18 pyparsing-2.2.0 pyscrypt-1.6.2 python-dateutil-2.7.3 radicale-storage-etesync-0.1.5 requests-2.19.1 six-1.11.0 urllib3-1.23 vobject-0.9.6.1
(issue) : ; etesync-dav --debug  --daemon
[7f9fd7563740] INFO: Starting Radicale
[7f9fd7563740] INFO: Authentication type is 'htpasswd'
[7f9fd7563740] INFO: Storage type is 'radicale_storage_etesync'
[7f9fd7563740] ERROR: An exception occurred during server startup: static_init() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/tmp/issue/lib/python3.6/site-packages/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/tmp/issue/lib/python3.6/site-packages/radicale/__main__.py", line 229, in serve
    application = Application(configuration, logger)
  File "/tmp/issue/lib/python3.6/site-packages/radicale/__init__.py", line 252, in __init__
    self.Collection = storage.load(configuration, logger)
  File "/tmp/issue/lib/python3.6/site-packages/radicale/storage.py", line 117, in load
    CollectionCopy.static_init()
TypeError: static_init() takes 0 positional arguments but 1 was given
(issue) : ; python3 --version
Python 3.6.6+
```

**Comment by tasn** [comment]
Try downgrading to Radicale 2.1.9 and let me know if this works. May as well be. :(

**Comment by stuart12** [comment]
Explicitly setting `Radicale==2.1.9` works but I don't understand what is going on as requirements.txt contains `Radicale==2.1.9`

```
: ; /usr/bin/python3 -m venv /tmp/issue2
: ; .  /tmp/issue2/bin/activate
(issue2) : ; pip install Radicale==2.1.9 etesync-dav
Collecting Radicale==2.1.9
Collecting etesync-dav
  Using cached https://files.pythonhosted.org/packages/58/03/d7ff3bb8281f14dda4f43c1a19649e5c0c451fd92074965f7d892bbd337a/etesync_dav-0.1.6-py3-none-any.whl
Collecting python-dateutil==2.6.1 (from Radicale==2.1.9)
  Using cached https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting vobject==0.9.5 (from Radicale==2.1.9)
Collecting appdirs>=1.4.3 (from etesync-dav)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting radicale-storage-etesync>=0.1.5 (from etesync-dav)
  Using cached https://files.pythonhosted.org/packages/58/b3/60e294dd83a606aae92250ec1369a628361836d0b0629a9a71e34f0d55d6/radicale_storage_etesync-0.1.5-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil==2.6.1->Radicale==2.1.9)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting etesync>=0.5.4 (from radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/01/aa/56014a882d855b74fa5c4b0dbf8202772cee2c3980d90b65256653af5df6/etesync-0.5.4-py3-none-any.whl
Collecting furl>=0.5 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting pyasn1>=0.2 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Collecting coverage>=4.3 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/3d/a0/b12090c40e0b8196b973962ec71c1c541a6c04af58ba5ad85683b3de251a/coverage-4.5.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting asn1crypto>=0.22 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting pyparsing>=2.2 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting packaging>=16.8 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Collecting pycparser>=2.17 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting orderedmultidict>=0.7 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting requests>=2.13 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting cryptography>=1.9 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/59/32/92cade62c645756a83598edf56289e9b19aae5370642a7ce690cd06bc72f/cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl
Collecting cffi>=1.10 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting py>=1.4 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/f3/bd/83369ff2dee18f22f27d16b78dd651e8939825af5f8b0b83c38729069962/py-1.5.4-py2.py3-none-any.whl
Collecting pyscrypt>=1.6 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting idna>=2.5 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting peewee<3.0,>=2.9 (from etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
Collecting certifi>=2017.4.17 (from requests>=2.13->etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/16/1f/50d729c104b21c1042aa51560da6141d1cab476ba7015d92b2111c8db841/certifi-2018.8.13-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.13->etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.13->etesync>=0.5.4->radicale-storage-etesync>=0.1.5->etesync-dav)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, vobject, Radicale, appdirs, orderedmultidict, furl, pyasn1, coverage, asn1crypto, pyparsing, packaging, pycparser, idna, certifi, urllib3, chardet, requests, cffi, cryptography, py, pyscrypt, peewee, etesync, radicale-storage-etesync, etesync-dav
Successfully installed Radicale-2.1.9 appdirs-1.4.3 asn1crypto-0.24.0 certifi-2018.8.13 cffi-1.11.5 chardet-3.0.4 coverage-4.5.1 cryptography-2.3.1 etesync-0.5.4 etesync-dav-0.1.6 furl-1.2.1 idna-2.7 orderedmultidict-1.0 packaging-17.1 peewee-2.10.2 py-1.5.4 pyasn1-0.4.4 pycparser-2.18 pyparsing-2.2.0 pyscrypt-1.6.2 python-dateutil-2.6.1 radicale-storage-etesync-0.1.5 requests-2.19.1 six-1.11.0 urllib3-1.23 vobject-0.9.5
(issue2) : ; etesync-dav --debug  
[7ff6701ab740] INFO: Starting Radicale
[7ff6701ab740] INFO: Authentication type is 'htpasswd'
[7ff6701ab740] INFO: Storage type is 'radicale_storage_etesync'
[7ff6701ab740] INFO: Rights type is 'owner_only'
[7ff6701ab740] INFO: Web type is 'internal'
[7ff6701ab740] INFO: Listening to 'localhost' on port 37358
[7ff6701ab740] INFO: Radicale server ready
^C[7ff6701ab740] INFO: Stopping Radicale
```

**Comment by tasn** [comment]
If you install from pip, it deosn't use requirements, but rather setup.py.
Grr, I guess I'll have to either pin radicale or fix it to support both.

**Comment by tasn** [comment]
It's a bug in radicale. Will open a PR there, in the meanwhile I'll push a warkaronud.

**Comment by tasn** [comment]
For reference: https://github.com/Kozea/Radicale/pull/862
