### ISSUE TITLE
Two issues with associate user account

### ISSUE THREAD

**Issue by jasom** [etesync/etesync-dav#317]
etesync-dav 0.32.1 NixOS

Account typically uses iOS, but I have also replicated the issues with cadaver.

1. Every other login fails on the client with a 500 error; radicale logs show a successful login
2. Once logged in, PROPFIND requests on any collection usually (but not always) return an error.  service logs from that error included below.

I have not been able to reproduce either of these problems on the main account, just the associate account.

```
Aug 21 16:41:11 mutsumi radicale[2390]: [2390/Thread-10526 (process_request_thread)] [INFO] PROPFIND request for '/ashley/hSakUK3Edxnfhjl_ejoRk8WTMGEctxz6/' with depth '1' received from ::1 using 'cadaver/0.24 neon/0.32.5'
Aug 21 16:41:11 mutsumi radicale[2390]: [2390/Thread-10526 (process_request_thread)] [INFO] Successful login: 'ashley'
Aug 21 16:41:13 mutsumi etesync-dav[2390]: [2390/Thread-10521] [ERROR] HTTP error 400! Code: 'field_errors'. Detail: 'Field validations failed.'
                                           Traceback (most recent call last):
                                             File "/nix/store/7vbywswsj5v7jdx8g4nyi376ixzfgqhw-etesync-dav-0.32.1/lib/python3.11/site-packages/etesync_dav/radicale/storage.py", line 84, in run
                                               etesync.sync()
                                             File "/nix/store/7vbywswsj5v7jdx8g4nyi376ixzfgqhw-etesync-dav-0.32.1/lib/python3.11/site-packages/etesync_dav/local_cache/__init__.py", line 92, in sync
                                               self.sync_collection(collection.uid)
                                             File "/nix/store/7vbywswsj5v7jdx8g4nyi376ixzfgqhw-etesync-dav-0.32.1/lib/python3.11/site-packages/etesync_dav/local_cache/__init__.py", line 157, in sync_collection
                                               self.push_collection(uid)
                                             File "/nix/store/7vbywswsj5v7jdx8g4nyi376ixzfgqhw-etesync-dav-0.32.1/lib/python3.11/site-packages/etesync_dav/local_cache/__init__.py", line 220, in push_collection
                                               item_mgr.batch(chunk_items, None, None)
                                             File "/nix/store/q5a0pvdw7brw5x87hb9yk6z4k7y302cp-python3.11-etebase-0.31.6/lib/python3.11/site-packages/etebase/__init__.py", line 298, in batch
                                               self._inner.batch(items_inner, deps_inner, _inner(fetch_options))
                                           etebase_python.Error: HTTP error 400! Code: 'field_errors'. Detail: 'Field validations failed.'
Aug 21 16:41:13 mutsumi radicale[2390]: [2390/Thread-10526 (process_request_thread)] [ERROR] An exception occurred during PROPFIND request on '/ashley/hSakUK3Edxnfhjl_ejoRk8WTMGEctxz6/': HTTP error 400! Code: 'field_errors'. Detail: 'Field>
```

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Using the Docker on Linux Mint 22.3 Cinnamon, I faced (while it used to work fine):</summary>

```
[2026-02-11 23:15:22 +0000] [1] [INFO] Radicale server ready
[2026-02-11 23:16:08 +0000] [1/Thread-1 (process_request_thread)] [INFO] REPORT request for '/Benjamin_Loison/KZ_e7ykAkYyWD3ECaZgHyCYAweZhp_Rm/' with depth '1' received from 172.17.0.1 using 'Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Thunderbird/147.0.1'
[2026-02-11 23:16:08 +0000] [1/Thread-1 (process_request_thread)] [INFO] Successful login: 'Benjamin_Loison'
[2026-02-11 23:16:08 +0000] [1/Thread-2] [ERROR] HTTP error 400! Code: 'field_errors'. Detail: 'Field validations failed.'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/etesync_dav/radicale/storage.py", line 84, in run
    etesync.sync()
  File "/usr/local/lib/python3.10/site-packages/etesync_dav/local_cache/__init__.py", line 96, in sync
    self.sync_collection(collection.uid)
  File "/usr/local/lib/python3.10/site-packages/etesync_dav/local_cache/__init__.py", line 161, in sync_collection
    self.push_collection(uid)
  File "/usr/local/lib/python3.10/site-packages/etesync_dav/local_cache/__init__.py", line 224, in push_collection
    item_mgr.batch(chunk_items, None, None)
  File "/usr/local/lib/python3.10/site-packages/etebase/__init__.py", line 298, in batch
    self._inner.batch(items_inner, deps_inner, _inner(fetch_options))
etebase_python.Error: HTTP error 400! Code: 'field_errors'. Detail: 'Field validations failed.'
[2026-02-11 23:16:08 +0000] [1/Thread-1 (process_request_thread)] [ERROR] An exception occurred during REPORT request on '/Benjamin_Loison/KZ_e7ykAkYyWD3ECaZgHyCYAweZhp_Rm/': HTTP error 400! Code: 'field_errors'. Detail: 'Field validations failed.'
```
</details>

which blocks downloading calendar updates on my Linux Mint Thunderbird, on my own Debian 13 Etebase instance.

```
docker run --env ETESYNC_URL=https://etesync.lemnoslife.com -it --rm -v etesync-dav:/data etesync/etesync-dav manage del Benjamin_Loison
```
```
Deleting user
```

```
docker run --env ETESYNC_URL=https://etesync.lemnoslife.com -it --rm -v etesync-dav:/data etesync/etesync-dav manage add Benjamin_Loison
```
<details>
<summary>Output:</summary>

```
Please enter the EteSync account password: 
Logging in
Saving config
Initializing account
User: Benjamin_Loison
Password: XXXXXXXXXXXXXXXX
```
</details>

solved the issue it seems.

Personal notes: [Benjamin_Loison/etesync-dav/issues/11](https://codeberg.org/Benjamin_Loison/etesync-dav/issues/11)
