### ISSUE TITLE
KeyError: ('logging', 'backtrace_on_debug')

### ISSUE THREAD

**Issue by besendorf** [etesync/etesync-dav#326]
With current version from github I get this error after running `pip install .` and `etesync-dav`
```
Traceback (most recent call last):
  File "/home/user/.local/bin/etesync-dav", line 163, in <module>
    radicale_main.run(radicale_args + sys.argv[1:])
  File "/home/user/.local/lib/python3.12/site-packages/etesync_dav/radicale_main/__init__.py", line 132, in run
    log.set_level(configuration.get("logging", "level"), configuration.get("logging", "backtrace_on_debug"))
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/radicale/config.py", line 391, in get
    raise KeyError(section, option)
KeyError: ('logging', 'backtrace_on_debug')
```

`etesync-dav --version` for example works as expected.

**Comment by tasn** [comment]
Sounds related to https://github.com/etesync/etesync-dav/pull/318 ?

Can you try pin an older version of radicale and see if that works? We should have a new release soon, just waiting for a few other changes from a contributor.

**Comment by CaseOf** [comment]
Hello,
I can confirm that current release version does not work on radicale >3.2
I did downgrade to radicale 3.1.9 and it works fine.

**Comment by suurt8ll** [comment]
Same here, downgrading to 3.1.9 solves the issue.
