### ISSUE TITLE
Error creating tasks with evolution

### ISSUE THREAD

**Issue by marzzzello** [etesync/etesync-dav#44]
When I try to create tasks with evolution I get the following error every time. Creating events is working fine. (From #10) 
```
[7f8a741af700] ERROR: An exception occurred during PUT request on '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/ee8e0a26e81f090a81475e61ef9f9752510eb71f.ics': vevent
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/peewee.py", line 6042, in get
  return clone.execute(database)[0]
File "/usr/lib/python3.7/site-packages/peewee.py", line 3729, in __getitem__
  return self.row_cache[item]
IndexError: list index out of range
```

<details>
  <summary>Full debug log</summary>
  
  ```
  etesync-dav -D 
[7fa2f9dbc600] INFO: Starting Radicale
[7fa2f9dbc600] INFO: Authentication type is 'htpasswd'
[7fa2f9dbc600] INFO: Storage type is 'radicale_storage_etesync'
[7fa2f9dbc600] INFO: Rights type is 'owner_only'
[7fa2f9dbc600] INFO: Web type is 'internal'
[7fa2f9dbc600] INFO: Listening to 'localhost' on port 37358
[7fa2f9dbc600] INFO: Radicale server ready
[7fa2f73fd700] INFO: PUT request for '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics' received from 127.0.0.1 using 'Evolution/3.30.4'
[7fa2f73fd700] DEBUG: Request headers:
{'CONTENT_LENGTH': '316',
 'CONTENT_TYPE': 'text/calendar; charset="utf-8"',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT_LANGUAGE': 'de-de, de;q=0.9',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'localhost:37358',
 'HTTP_IF_NONE_MATCH': '*',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_PREFER': 'return=minimal',
 'HTTP_USER_AGENT': 'Evolution/3.30.4',
 'PATH_INFO': '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'PUT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'localhost',
 'SERVER_PORT': '37358',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x7fa2f8593d38>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=6>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
[7fa2f73fd700] DEBUG: Sanitized script name: ''
[7fa2f73fd700] DEBUG: Sanitized path: '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics'
[7fa2f73fd700] INFO: Successful login: 'marzzzello'
[7fa2f73fd700] DEBUG: Request content:
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Ximian//NONSGML Evolution Calendar//EN
VERSION:2.0
BEGIN:VTODO
UID:a1fc39aefa19c87188c8828d2984ac70b9feb896
DTSTAMP:20190126T154817Z
SUMMARY:new task...
PRIORITY:0
CLASS:PUBLIC
CREATED:20190126T162820Z
LAST-MODIFIED:20190126T162820Z
END:VTODO
END:VCALENDAR

[7fa2f73fd700] ERROR: An exception occurred during PUT request on '/marzzzello/a315debd27d31cd890fcdebb084d613d11297830afa3c5b84dde4db5ca6dc9d7/a1fc39aefa19c87188c8828d2984ac70b9feb896.ics': vevent
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/peewee.py", line 6042, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.7/site-packages/peewee.py", line 3729, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 389, in get
    return self.get_content_class()._from_cache(self._cache_obj.content_set.where(pim.Content.uid == uid).get())
  File "/usr/lib/python3.7/site-packages/peewee.py", line 6047, in get
    (clone.model, sql, params))
etesync.pim.ContentDoesNotExist: <Model: Content> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS "t1" WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?)) LIMIT ? OFFSET ?
Params: [22, 'a1fc39aefa19c87188c8828d2984ac70b9feb896', 1, 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/radicale_storage_etesync/__init__.py", line 357, in upload
    item = self.get(href)
  File "/usr/lib/python3.7/site-packages/radicale_storage_etesync/__init__.py", line 335, in get
    etesync_item = self.collection.get(uid)
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 391, in get
    raise exceptions.DoesNotExist(e)
etesync.exceptions.DoesNotExist: <Model: Content> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."journal_id", "t1"."uid", "t1"."content", "t1"."new", "t1"."dirty", "t1"."deleted" FROM "content" AS "t1" WHERE (("t1"."journal_id" = ?) AND ("t1"."uid" = ?)) LIMIT ? OFFSET ?
Params: [22, 'a1fc39aefa19c87188c8828d2984ac70b9feb896', 1, 0]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/vobject/base.py", line 529, in __getattr__
    return self.contents[toVName(name)][0]
KeyError: 'vevent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/radicale/__init__.py", line 332, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.7/site-packages/radicale/__init__.py", line 505, in _handle_request
    environ, base_prefix, path, user)
  File "/usr/lib/python3.7/site-packages/radicale/__init__.py", line 948, in do_PUT
    new_item = parent_item.upload(href, items[0])
  File "/usr/lib/python3.7/site-packages/radicale_storage_etesync/__init__.py", line 361, in upload
    etesync_item = self.collection.get_content_class().create(self.collection, content)
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 290, in create
    ret.content = content
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 300, in content
    self.uid = self.__class__.get_uid(content)
  File "/usr/lib/python3.7/site-packages/etesync/api.py", line 315, in get_uid
    return vobj.vevent.uid.value
  File "/usr/lib/python3.7/site-packages/vobject/base.py", line 531, in __getattr__
    raise AttributeError(name)
AttributeError: vevent
```
</details>

**Comment by tasn** [comment]
Thanks for reporting.

Just to verify: when you access the etesync-dav url using your web browser, is a1fc39aefa19c87188c8828d2984ac70b9feb896 shown as supporting tasks?

**Comment by marzzzello** [comment]
Where can I see `a1fc39aefa19c87188c8828d2984ac70b9feb896` in the webinterface? It's not the URL of the calendar/taks list right?
But of course I tried it with a calendar that supports task. It also made no difference if I choose `tasks` as type or `calendar, journal and tasks`

**Comment by marzzzello** [comment]
I just looked again in the browser and it was of type calendar. I am sure that I choose tasks.
Then I wanted to change it but it always goes back to calendar. Even when I create a new calendar with all 3 types it goes back to calendar only

**Comment by tasn** [comment]
You can't change the type of a collection in EteSync. In order to use tasks you'd need to first make sure you have a tasks collection. It'll be automatically created for you from the Android app if you have Open Tasks installed on Android. Alternatively, you'd need to log in once from the web app, and it'll automatically add a tasks journal for you.

You can also try creating a *new tasks only* collection from the either the etesync-dav web interface or Evolution, but I don't know if these two methods actually work as I haven't tested them.

**Comment by marzzzello** [comment]
So after finding out that the Etesync version from F-Droid is outdated and had no support for OpenTasks I got tasks working :+1: . I can only create task lists with the Android app but not in the webinterface.

**Comment by tasn** [comment]
Good to know that the web interface is incomplete in that regard.

Sorry about your trouble. The F-droid builds have been failing for a few weeks now. They finally fixed things yesterday, and it looks like latest EteSync will be available on f-droid tonight! :)
