### ISSUE TITLE
Bad REPORT request

### ISSUE THREAD

**Issue by idmyn** [etesync/etesync-dav#64]
Not sure how related this is to #16 or whether this is more of an issue with the etesync web client import feature but I figured I'd flag it up here.

I had imported a large (~1400 events) .ics file through the etesync web client (client.etesync.com) into a fresh calendar, and although it didn't throw up any errors at that stage, and appeared fine in the web client view, when trying to view the calendar in Calendar.app via etesync-dav the calendar appeared but without any events. Calendar.app gave the following error message:

<img width="404" alt="Screenshot 2019-04-17 at 11 44 28" src="https://user-images.githubusercontent.com/4623769/56283260-19fb2480-6109-11e9-935a-327e30dfc285.png">

Console output:
```
[700002bc5000] WARNING: Bad REPORT request on '/dmy@tuta.io/f8d2941c4aa242e53ad9c004041867553b90d64545b0ff3107c9bdfa20702de2/': Failed to filter item '02hkpnm2uhhh1tmrppnch1thus@google.com.ics' from 'dmy@tuta.io/f8d2941c4aa242e53ad9c004041867553b90d64545b0ff3107c9bdfa20702de2': Main component missing
WARNING:radicale:Bad REPORT request on '/dmy@tuta.io/f8d2941c4aa242e53ad9c004041867553b90d64545b0ff3107c9bdfa20702de2/': Failed to filter item '02hkpnm2uhhh1tmrppnch1thus@google.com.ics' from 'dmy@tuta.io/f8d2941c4aa242e53ad9c004041867553b90d64545b0ff3107c9bdfa20702de2': Main component missing
ERROR:root:No module named 'pytz'
```
(there were lots of 'pytz' errors above and below but I've only included one)

Notably, when I deleted the calendar through the etesync android app, made a new calendar, and imported _the same file_ through the android app, I didn't have any trouble with etesync-dav.

**Comment by tasn** [comment]
Could you please try creating another calendar (a temporary one), import again through the web client, and see if it fails again? I wonder if it was a one time thing, or a consistent issue with the web client import.

I wonder if the problem is with the sheer size or with one of the entries. The import from the app is well tested with calendars of all sizes and a variety of odd events. The web import is newer so not as much.

**Comment by idmyn** [comment]
I've tried this again and found very similar results. Calendar.app gave a near-identical error message, but reported server response of "500" instead of "400".

The console output (in addition to a "main component missing" error that looks very similar to what I reported the first time) included this (potentially helpful?) response:
```
[70000c6dc000] ERROR: An exception occurred during PROPFIND request on '/dmy@tuta.io/64658fa1644579c12c65286902aeb7a5dc558fa9458fc911a539755fdd570715/': 'VTIMEZONE components must contain a valid TZID'
ERROR:radicale:An exception occurred during PROPFIND request on '/dmy@tuta.io/64658fa1644579c12c65286902aeb7a5dc558fa9458fc911a539755fdd570715/': 'VTIMEZONE components must contain a valid TZID'
```

**Comment by tasn** [comment]
That's interesting. This error essentially means that you have a bad entry in your collection, so it actually didn't import things correctly. Could you maybe run `etesync-dav -D` and see if we get more useful information?

**Comment by idmyn** [comment]
Done. I've now got an output file with ~1000 lines! Any tips for what I should be looking for?

**Comment by tasn** [comment]
The above error. It should have a stack trace and potentially extra information (like the request sent/response built) around it.

**Comment by idmyn** [comment]
Makes sense, haha. Here's what my search brought up - any use?
```
[70000355c000] ERROR: An exception occurred during PROPFIND request on '/dmy@tuta.io/64658fa1644579c12c65286902aeb7a5dc558fa9458fc911a539755fdd570715/': 'VTIMEZONE components must contain a valid TZID'
Traceback (most recent call last):
  File "site-packages/radicale/__init__.py", line 332, in __call__
  File "site-packages/radicale/__init__.py", line 505, in _handle_request
  File "site-packages/radicale/__init__.py", line 813, in do_PROPFIND
  File "site-packages/radicale/xmlutils.py", line 812, in propfind
  File "site-packages/radicale/xmlutils.py", line 909, in _propfind_response
  File "site-packages/radicale_storage_etesync/__init__.py", line 144, in etag
  File "site-packages/vobject/base.py", line 254, in serialize
  File "site-packages/vobject/icalendar.py", line 1001, in serialize
  File "site-packages/vobject/behavior.py", line 85, in validate
  File "site-packages/vobject/base.py", line 124, in validate
  File "site-packages/vobject/icalendar.py", line 1069, in validate
vobject.base.ValidateError: 'VTIMEZONE components must contain a valid TZID'
ERROR:radicale:An exception occurred during PROPFIND request on '/dmy@tuta.io/64658fa1644579c12c65286902aeb7a5dc558fa9458fc911a539755fdd570715/': 'VTIMEZONE components must contain a valid TZID'
Traceback (most recent call last):
  File "site-packages/radicale/__init__.py", line 332, in __call__
  File "site-packages/radicale/__init__.py", line 505, in _handle_request
  File "site-packages/radicale/__init__.py", line 813, in do_PROPFIND
  File "site-packages/radicale/xmlutils.py", line 812, in propfind
  File "site-packages/radicale/xmlutils.py", line 909, in _propfind_response
  File "site-packages/radicale_storage_etesync/__init__.py", line 144, in etag
  File "site-packages/vobject/base.py", line 254, in serialize
  File "site-packages/vobject/icalendar.py", line 1001, in serialize
  File "site-packages/vobject/behavior.py", line 85, in validate
  File "site-packages/vobject/base.py", line 124, in validate
  File "site-packages/vobject/icalendar.py", line 1069, in validate
vobject.base.ValidateError: 'VTIMEZONE components must contain a valid TZID'
```

**Comment by tasn** [comment]
I was hoping we would get to see the actually broken event, though unfortunately it's not the case.

Maybe try adding `print(self.etesync_item.content)` in the beginning of the function `etag` just before the return in line 144 of `site-packages/radicale_storage_etesync/__init__.py`. That should add some more information.

**Comment by idmyn** [comment]
No such luck, debug output was the same. My ```def etag(self)``` function started at line 134 and returned at 136 (before I made the edit) - might that have something to do with it? There's also a ```def etag(self)``` at line 222, but I assumed line 134 would be the one you meant. The function I edited returns with ```get_etag(self.item.serialize())```

**Comment by tasn** [comment]
It looks like you have multiple versions installed and you're editing the wrong one. I took line 144 directly from your backtrace from above:
`  File "site-packages/radicale_storage_etesync/__init__.py", line 144, in etag`

**Comment by idmyn** [comment]
Ahh. I've tried running ```locate``` in terminal (and updating its database), but it only finds one file: ```/usr/local/lib/python3.7/site-packages/radicale_storage_etesync/__init__.py```, which is the file I edited. I've checked the corresponding directories for other python versions but there no sign of radicale. Any ideas how I might find the correct file?

**Comment by tasn** [comment]
This path looks correct. One thing you can try is using strace (run `strace python etesync-dav`) and then try to find the correct file in the output. I'm sure there's a more python specific way, but I have no idea. :)

**Comment by tasn** [comment]
Thanks @anthonymvicente. I don't think it's related, though I'll have to take a better look at it to be sure.

I'm also pretty sure I've seen this error before, though I don't remember what was the cause. Could you please open a new ticket for this issue and we can discuss it there? Thanks, and sorry for the slow reply.

**Comment by anthonymvicente** [comment]
@tasn Apologies, I was originally creating an issue, and this popped up as possibly related and I misdiagnosed it. I've created a new issue with my problem, thanks for letting me know!
https://github.com/etesync/etesync-dav/issues/112

**Comment by tasn** [comment]
Nothing to be sorry about, and thanks a lot for reporting! I'll follow up with the other ticket next week (I'm at FOSDEM this weekend).
